config/routes.rb
Rails.application.routes.draw do

  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end
  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  mount Blacklight::Engine => '/'
  root to: "catalog#index"
  resources :resources

#  get '/resources/random_output', to: 'resources#random_output'
  get 'chatgpt_image_output', action: :chatgpt_image, controller: 'resources'
  get 'random_output', action: :random_output, controller: 'resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    q = params[:q]
    @q = q
    
    unless q.blank?
      @res = Resource.search do
        fulltext q
      end
    end
  end
end

app/views/search/index.html.haml
# app/views/search/index.html.haml

= simple_form_for :search, :method=>:get do |f|
  = text_field_tag 'q', @q, :style=>"width: 240px;"
  = f.submit 'Search'


- if !@res
  %hr
  Not found


- else
  Found #{@res.total}
  %hr
  - @res.results.each do |item|
    = link_to item.name, resource_path(item)
  %br