config/routes.rb
Rails.application.routes.draw do

  concern :marc_viewable, Blacklight::Marc::Routes::MarcViewable.new
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end
  devise_for :users
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns [:exportable, :marc_viewable]
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end
  mount Blacklight::Engine => '/'
  root to: "catalog#index"
  resources :resources

#  get '/resources/random_output', to: 'resources#random_output'
  get 'chatgpt_image_output', action: :chatgpt_image, controller: 'resources'
  get 'random_output', action: :random_output, controller: 'resources'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select([["Art", "Art"], ["Math", "Math"], ["Science", "Science"], ["Travel", "Travel"]]), prompt: "Select a category" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table style="width: 100%; border-collapse: collapse; table-layout: fixed;">
  <thead>
    <tr>
      <th style="width: 4%;"></th>
      <th style="width: 4%;"></th>
      <th style="width: 5%;"></th>
      <th style="width: 20%;">Title</th>
      <th style="width: 10%;">Category</th>
      <th style="width: 30%;">Description</th>
      <th style="width: 27%;">Url</th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= resource.title %></td>
        <td><%= resource.category %></td>
        <td style="word-wrap: break-word; white-space: normal;"><%= resource.description %></td>
        <td><%= link_to resource.url, resource.url, target: '_blank' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= link_to @resource.title, @resource.url, target: '_blank' %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @resource.url, @resource.url, target: '_blank' %>
</p>

<p>
  <strong>Category:</strong>
  <%= @resource.category %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>